import os
from datetime import date

from utils.TradeFriendsendemail import send_email_with_attachments
from utils.logger import get_logger
from config.TradeFriendSettings import (

    EMAIL_Enabled,
    EMAIL_SUBJECT_TEMPLATE,
    EMAIL_BODY_TEMPLATE,
    RECEIVER_EMAILS,
    SENDER_EMAIL,
    SENDER_PASSWORD
)





logger = get_logger(__name__)


class TradeFriendDailyScanReportService:
    """
    PURPOSE (PHASE-6):
    - Send DAILY SCAN REPORT via email
    - Attach CSV + PDF generated by WatchlistEngine
    - No scan logic
    - No file generation logic
    """

    @staticmethod
    def send_email(scan_date: str, scan_results: list, attachments: list):

        if not EMAIL_Enabled:
            logger.info("📧 Email disabled — skipping daily scan report")
            return

        if not attachments:
            logger.warning("📧 No attachments found — skipping email")
            return

        valid_files = [f for f in attachments if os.path.exists(f)]
        if not valid_files:
            logger.warning("📧 Attachments missing on disk — skipping email")
            return

        # Already list[dict]
        scan_results = list(scan_results)

        if not scan_results:
            scan_results = []
        
        # Normalize structure
        if isinstance(scan_results, list):
            if scan_results and isinstance(scan_results[0], str):
                # Convert list of symbols to dict format
                scan_results = [{"symbol": s} for s in scan_results]
        elif isinstance(scan_results, str):
            scan_results = [{"symbol": scan_results}]
        else:
            scan_results = []
        
        subject = f"📊 TradeFriend Daily Scan Report — {scan_date}"

        symbols = [r.get("symbol", "") for r in scan_results]
        strategies = sorted(set(r.get("strategy", "") for r in scan_results))

        body = f"""
    TradeFriend — Daily Scan Report
    Date: {scan_date}

    Total Qualified Stocks: {len(scan_results)}
    Strategies Triggered: {', '.join(strategies)}

    Symbols:
    {', '.join(symbols)}

    Attachments:
    - CSV (Full Scan Data)
    - PDF (Human-readable Summary)

    ⚠️ This is an automated report.
    📌 Trades are NOT executed at this stage.
        """.strip()

        try:
            send_email_with_attachments(
                sender_email=SENDER_EMAIL,
                sender_password=SENDER_PASSWORD,
                receiver_emails=RECEIVER_EMAILS,
                subject=subject,
                body=body,
                file_paths=valid_files
            )

            logger.info(f"📧 Daily scan report email sent to {RECEIVER_EMAILS}")

        except Exception as e:
            logger.exception(f"❌ Failed to send scan report email: {e}")
